/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUserRouteImport } from './routes/_app.user'
import { Route as AppTunnelRouteImport } from './routes/_app.tunnel'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNodeRouteImport } from './routes/_app.node'
import { Route as AppLimitRouteImport } from './routes/_app.limit'
import { Route as AppForwardRouteImport } from './routes/_app.forward'
import { Route as AppConfigRouteImport } from './routes/_app.config'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUserRoute = AppUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppRoute,
} as any)
const AppTunnelRoute = AppTunnelRouteImport.update({
  id: '/tunnel',
  path: '/tunnel',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNodeRoute = AppNodeRouteImport.update({
  id: '/node',
  path: '/node',
  getParentRoute: () => AppRoute,
} as any)
const AppLimitRoute = AppLimitRouteImport.update({
  id: '/limit',
  path: '/limit',
  getParentRoute: () => AppRoute,
} as any)
const AppForwardRoute = AppForwardRouteImport.update({
  id: '/forward',
  path: '/forward',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/config': typeof AppConfigRoute
  '/forward': typeof AppForwardRoute
  '/limit': typeof AppLimitRoute
  '/node': typeof AppNodeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/tunnel': typeof AppTunnelRoute
  '/user': typeof AppUserRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/config': typeof AppConfigRoute
  '/forward': typeof AppForwardRoute
  '/limit': typeof AppLimitRoute
  '/node': typeof AppNodeRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/tunnel': typeof AppTunnelRoute
  '/user': typeof AppUserRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/forward': typeof AppForwardRoute
  '/_app/limit': typeof AppLimitRoute
  '/_app/node': typeof AppNodeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/tunnel': typeof AppTunnelRoute
  '/_app/user': typeof AppUserRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/config'
    | '/forward'
    | '/limit'
    | '/node'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/tunnel'
    | '/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/config'
    | '/forward'
    | '/limit'
    | '/node'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/tunnel'
    | '/user'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/config'
    | '/_app/forward'
    | '/_app/limit'
    | '/_app/node'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_app/tunnel'
    | '/_app/user'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/user': {
      id: '/_app/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AppUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tunnel': {
      id: '/_app/tunnel'
      path: '/tunnel'
      fullPath: '/tunnel'
      preLoaderRoute: typeof AppTunnelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/node': {
      id: '/_app/node'
      path: '/node'
      fullPath: '/node'
      preLoaderRoute: typeof AppNodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/limit': {
      id: '/_app/limit'
      path: '/limit'
      fullPath: '/limit'
      preLoaderRoute: typeof AppLimitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forward': {
      id: '/_app/forward'
      path: '/forward'
      fullPath: '/forward'
      preLoaderRoute: typeof AppForwardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfigRoute: typeof AppConfigRoute
  AppForwardRoute: typeof AppForwardRoute
  AppLimitRoute: typeof AppLimitRoute
  AppNodeRoute: typeof AppNodeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTunnelRoute: typeof AppTunnelRoute
  AppUserRoute: typeof AppUserRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfigRoute: AppConfigRoute,
  AppForwardRoute: AppForwardRoute,
  AppLimitRoute: AppLimitRoute,
  AppNodeRoute: AppNodeRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTunnelRoute: AppTunnelRoute,
  AppUserRoute: AppUserRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
