// Package nftgeneration contains the safety-critical primitives shared by the
// nft reporter and agent while rules move between table generations.
package nftgeneration

import (
	"encoding/hex"
	"fmt"
	"io"
	"strings"
	"unicode"
)

const (
	// LegacyTable is the historical, non-generated Flux nft table.
	LegacyTable = "flux_panel"
	// ActiveTableMarkerPath is the durable handoff marker shared by the
	// reporter and every process that mutates Flux nft rules.
	ActiveTableMarkerPath = "/var/lib/flux-nftables/active-table"
	// LockPath serializes generation handoffs and agent rule operations.
	LockPath = "/run/flux-nftables/flow-reporter.lock"
	// RetryableErrorPrefix is the stable wire prefix used when an agent command
	// cannot run because the generation handoff lock is owned elsewhere.
	RetryableErrorPrefix = "nft generation handoff in progress; retry operation:"
	// MaxRuleBatchItems and MaxRuleBatchBytes bound agent atomic add/delete
	// requests shared with the panel-side command producer.
	MaxRuleBatchItems = 10_000
	MaxRuleBatchBytes = 2 << 20

	generationPrefix = LegacyTable + "_g_"
	generationBytes  = 16
)

// ValidateTableName accepts only the historical table or a table generated by
// NewTableName. Keeping this grammar small makes table names safe as nft argv
// values and transaction tokens.
func ValidateTableName(table string) error {
	if table == LegacyTable {
		return nil
	}
	if len(table) != len(generationPrefix)+hex.EncodedLen(generationBytes) ||
		!strings.HasPrefix(table, generationPrefix) {
		return fmt.Errorf("invalid Flux nft table name %q", table)
	}
	for _, c := range table[len(generationPrefix):] {
		if c < '0' || c > '9' && c < 'a' || c > 'f' {
			return fmt.Errorf("invalid Flux nft table name %q", table)
		}
	}
	return nil
}

// NewTableName reads exactly 128 bits from random and returns a validated,
// lowercase generation table name. The reader is injected to keep entropy
// failure and deterministic generation testable.
func NewTableName(random io.Reader) (string, error) {
	if random == nil {
		return "", fmt.Errorf("generate Flux nft table name: nil random reader")
	}
	raw := make([]byte, generationBytes)
	if _, err := io.ReadFull(random, raw); err != nil {
		return "", fmt.Errorf("generate Flux nft table name: %w", err)
	}
	return generationPrefix + hex.EncodeToString(raw), nil
}

// RewriteCanonicalRule changes only the table token of a canonical rule. It
// deliberately does not invoke a shell or perform a general text replacement.
func RewriteCanonicalRule(rule, targetTable string) (string, error) {
	if err := ValidateTableName(targetTable); err != nil {
		return "", err
	}
	if rule == "" || strings.TrimSpace(rule) != rule {
		return "", fmt.Errorf("nft rule has surrounding whitespace")
	}
	if strings.IndexFunc(rule, func(r rune) bool {
		return unicode.IsControl(r) || unicode.IsSpace(r) && r != ' ' || r == ';' || r == '#'
	}) >= 0 {
		return "", fmt.Errorf("nft rule contains unsafe characters")
	}

	fields := strings.Split(rule, " ")
	for _, field := range fields {
		if field == "" {
			return "", fmt.Errorf("nft rule must use single ASCII spaces")
		}
	}
	if len(fields) < 6 || fields[0] != "add" || fields[1] != "rule" ||
		fields[2] != "inet" || fields[3] != LegacyTable {
		return "", fmt.Errorf("unexpected canonical nft rule prefix")
	}
	switch fields[4] {
	case "prerouting", "forward", "postrouting":
	default:
		return "", fmt.Errorf("unexpected canonical nft rule chain")
	}

	fields[3] = targetTable
	return strings.Join(fields, " "), nil
}
